[pytest]
DJANGO_SETTINGS_MODULE = project.settings
python_files = tests.py test_*.py *_tests.py
addopts = 
    --doctest-modules 
    --strict-markers 
    --tb=short -q
    -rP
markers =
    slow: run slow tests are slow
    fast: run fast tests are fast
